accounts/urls.py
"""Urlconf for accounts app"""
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="accounts/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("change_password/", views.change_password, name="change_password"),
]

lesson_planner/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("laoban/", admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("hello/", views.HelloPage.as_view(), name="hello"),
    path("goodbye/", views.GoodbyePage.as_view(), name="goodbye"),
    path("games/", views.GamesPage.as_view(), name="games"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("lessons/", include("lessons.urls", namespace="lessons")),
]

lessons/urls.py
"""Urls file for lessons app"""
from django.urls import path
from . import views

app_name = "lessons"

urlpatterns = [
    path("all/", views.LessonListView.as_view(), name="lesson_list"),
    path("id/<pk>/", views.LessonDetailView.as_view(), name="lesson_detail"),
    path("create-basic/", views.CreateBasicLessonView.as_view(), name="create_basic"),
    path("create-arrow/", views.CreateArrowLessonView.as_view(), name="create_arrow"),
    path(
        "create-boomerang/",
        views.CreateBoomerangLessonView.as_view(),
        name="create_boomerang",
    ),
    path(
        "create-patchwork/",
        views.CreatePatchworkLessonView.as_view(),
        name="create_patchwork",
    ),
    path("delete/<pk>/", views.DeleteLessonView.as_view(), name="delete"),
    path("update/<pk>/", views.UpdateLessonView.as_view(), name="update_basic"),
    path(
        "update-arrow/<pk>/", views.UpdateArrowLessonView.as_view(), name="update_arrow"
    ),
    path(
        "update-boomerang/<pk>/",
        views.UpdateBoomerangLessonView.as_view(),
        name="update_boomerang",
    ),
    path(
        "update-patchwork/<pk>/",
        views.UpdatePatchworkLessonView.as_view(),
        name="update_patchwork",
    ),
    path("by/<username>/", views.LessonListByUser.as_view(), name="by_user"),
    path("with-tag/all/", views.TagListView.as_view(), name="tag_list"),
    path("with-tag/<slug:slug>/", views.TagDetailView.as_view(), name="tag_detail"),
    path("from-book/all/", views.BookListView.as_view(), name="book_list"),
    path("from-book/<slug:slug>/", views.BookDetailView.as_view(), name="book_detail"),
]

templates/about.html
{% extends "base.html" %}

{% block title %}- Home{% endblock %}

{% block header %}
  <h1 class="header-title">About Lesson Planner</h1>
{% endblock %}

{% block content %}
  <div class="about">
    <p>Lesson Planner is an application for faster lesson planning for ESL classes.</p>
    <p>Made for teachers by teachers</p>
    <p>This project is free and always in develepment so new features will roll out regularly</p>

    <h3>Current Features</h3>
    <ul class="collection">
      <li class="collection-item"><i class="material-icons">check</i> Basic account functionality: signup, login. logout, change password</li>
      <li class="collection-item"><i class="material-icons">check</i> Create, edit and delete new lesson plans</li>
      <li class="collection-item"><i class="material-icons">check</i> Filter lesson plans by tags</li>
      <li class="collection-item"><i class="material-icons">check</i> Filter lesson plans by books</li>
      <li class="collection-item"><i class="material-icons">check</i> Add YouTube video url and preview a video on lesson plan details page</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Templates: Choose from a variety of lesson plan types or methodologies (PPP, ESA, TTT, etc.)</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> WYSIWYG editor in lesson plan creation/editing form</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Recommendations: On lesson creating form, pick tags to see recommended related activities or games</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> File uploads: upload worksheets, flashcards and other files</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Export: save lessons in .doc or .pdf</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Custom export templates: create your own templates with your name/school logo etc.</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Reports: section for interactive and fast student reports creation</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Games/Activities separate section: New section dedicated to classroom games/activities only</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Comments: post comments lesson plans, activites</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Advanced accounts: add personal info, avatar, list of favorite lesson plans/activities</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Voting for games and activities: rate activities and help us find the best ones, save to favorites</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Badges: Receive badges for created lesson plans or adding highly rated activities</li>
      <li class="collection-item"><i class="material-icons">check_box_outline_blank</i> Social auth: login with your social media account</li>
    </ul>
  </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Lesson Planner {% block title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  {% load analytical %}
  {% analytical_head_top %}{% analytical_head_bottom %}
  <!-- Materialize CSS -->
  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/materialize.css' %}">
  <!-- Custom styles -->
  <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/styles.css' %}">
  <!-- Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  
  {% block head %}{% endblock %}
</head>
<body>
  
  <main>
    <!-- Header -->
    {% include 'header.html' %}

    <!-- Container -->
    <div class="container">
      {% block header %}{% endblock %}

      {% block content %}{% endblock %}
    </div>
  </main>

  <!-- Footer -->
  <footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">ESL Lesson Planner</h5>
          <p class="grey-text text-lighten-4"></p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li>
              <a class="grey-text text-lighten-3" href="https://github.com/denibulkashvili/LessonPlannerSocial">
                GitHub
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2019 ESL Lesson Planner
      </div>
    </div>
  </footer>

  <script src="{% static 'js/materialize.min.js' %}"></script>
  <script>
    M.AutoInit();
    var editor = new MediumEditor('.editable', {
        placeholder: false
    });
  </script>
</body>
</html>

templates/games.html
{% extends "base.html" %}

{% block title %}- Home{% endblock %}

{% block header %}
  <h1 class="header-title">Online Games</h1>
{% endblock %}

{% block content %}
  <div class="games">
    Here are some games I built to use for ESL classes: 
    <ul>
      <li><a href="https://card-matching-game.herokuapp.com">Card Matching Game</a></li>
    </ul>

    Other online games:
    <ul>
      <li><a href="https://www.gamestolearnenglish.com/clothes-game/">He's/She's wearing (Clothes game)</a></li>
      <li><a href="https://www.abcya.com/games/pizza">Make a Pizza</a></li>
    </ul>
  </div>
{% endblock %}

templates/goodbye.html
{% extends "base.html" %}

{% block title %}- Thank You{% endblock %}

{% block header %}
  <h1 class="header-title">Thanks for visiting. Come back soon.</h1>
{% endblock %}

{% block content %}
  
{% endblock %}

templates/header.html
<header>
    <nav>
      <div class="nav-wrapper">
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li> <a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'lessons:lesson_list' %}">All Lessons</a></li>
          <li><a href="{% url 'lessons:tag_list' %}">Tags</a></li>
          <li><a href="{% url 'lessons:book_list' %}">Books</a></li>
          <li><a href="{% url 'games' %}">Games</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'lessons:by_user' username=user.username %}">My Lessons</a></li>
            <!-- Dropdown Trigger -->
            <li>
              <a class="dropdown-trigger" href="#!" data-target="dropdown1">
                Add Lesson Plan
                <i class="material-icons left">add</i> 
                <i class="material-icons right">arrow_drop_down</i>
              </a>
            </li>
            <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- Dropdown Structure -->
    <ul id="dropdown1" class="dropdown-content">
      <li><a href="{% url 'lessons:create_basic' %}">1. Basic Lesson Template</a></li>
      <li class="divider"></li>
      <li><a href="{% url 'lessons:create_arrow' %}">2. ESA Staright Arrow</a></li>
      <li><a href="{% url 'lessons:create_boomerang' %}">3. ESA Boomerang</a></li>
      <li><a href="{% url 'lessons:create_patchwork' %}">4. ESA Patchwork</a></li>
      <li class="divider"></li>
      <li>
        <a class="waves-effect waves-light modal-trigger" href="#lesson-types-help">
          <i class="material-icons right">help_outline</i>
          Lesson Types Help
        </a>
      </li>
      <li class="divider"></li>
      <li><a href="#!">More templates coming up ...</a></li>
    </ul>
    
    <ul class="sidenav" id="mobile-demo">
      <li> <a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'lessons:lesson_list' %}">Lessons</a></li>
      <li><a href="{% url 'lessons:tag_list' %}">Tags</a></li>
      <li><a href="{% url 'lessons:book_list' %}">Books</a></li>
      <li><a href="{% url 'games' %}">Games</a></li>
      <li><a href="{% url 'about' %}">About</a></li>
      {% if user.is_authenticated %}
        <li><a href="{% url 'lessons:by_user' username=user.username %}">My Lessons</a></li>
        <li>
          <ul class="collapsible">
            <li>
              <a href="#!"> 
              <div class="collapsible-header">
                  Add Lesson Plan
                <i class="material-icons right">arrow_drop_down</i>
              </div>
              </a>
              <div class="collapsible-body">
                <span>
                  <ul>  
                    <li class="divider"></li>
                    <li><a href="{% url 'lessons:create_basic' %}">1. Basic Lesson Template</a></li>
                    <li><a href="{% url 'lessons:create_arrow' %}">2. ESA Staright Arrow</a></li>
                    <li><a href="{% url 'lessons:create_boomerang' %}">3. ESA Boomerang</a></li>
                    <li><a href="{% url 'lessons:create_patchwork' %}">4. ESA Patchwork</a></li>
                    <li class="divider"></li>
                    <li>
                      <a class="waves-effect waves-light modal-trigger" href="#lesson-types-help">
                        <i class="material-icons right">help_outline</i>
                        Lesson Types Help
                      </a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="#!">More templates coming up ...</a></li>
                    <li class="divider"></li>
                  </ul>
                </span>
              </div>          
            </li>
          </ul>
        </li>
        <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
        <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
      {% else %}
        <li><a href="{% url 'accounts:login' %}">Login</a></li>
        <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
      {% endif %}
    </ul>

    <!-- Lesson Types Help Modal -->
    <div id="lesson-types-help" class="modal">
      <div class="modal-content">
        <h3>Lesson Types</h3>
        <h4>Basic Lesson</h4>
        <p>Generic lesson type that is not limited to a specific lesson structure.</p>
        <h4>ESA Methodology</h4>
        <p>ESA is a common methodology that stands for <b>engage</b>, <b>study</b>, and <b>activate</b> and is 
          designed to keep the students interested, motivated, and eager to learn more.
        </p>
        <p><b>ESA Phases</b>:
          <ol>
            <li><b>Engage phase</b> (Warm-Up): getting the students interested in the class through a game, pictures, audio, video etc.</li>
            <li><b>Study phase</b>: focusing on any aspect of the language, such as grammar or vocabulary and pronunciation 
              and can be done in many different styles, from group examination of a text, to discovery related topic vocabulary, 
              to the teacher giving an explanation of a grammatical pattern.</li>
            <li><b>Activate stage</b>: putting things learned in lesson in action by gettin students to use the language as communicatively as they can, 
              through such activities as discussions, role-play, story building, simulations, debates etc.
            </li>
          </ol>
        </p>
        <h4>Types of ESA Lessons</h4>
        <h5>ESA sraight arrows sequence</h5>
        <p>Straight arrow best for the beginners because they need guidance of the teacher. 
          ESA Straight Arrows sequence is a type of teaching sequence takes students in a straight line: first the teacher gets the class interested and Engaged, 
          then the students Study something and they then try to Activate it by putting it into practice. </p>
        <h5>Boomerang sequence</h5>
        <p>The Boomerang approach after the Engage (E) phase, gets students to perform a task (A) using all and/or any language they know 
          and only then does the teacher go back to the language Study (S).
           The Study phase is then undertaken based on what the teacher witnessed in the students language performance. 
           The teacher in short will fill in the gaps of the students knowledge. To check that learning has taken place the students are then re-activated (A). 
           It may also be more appropriate for students at intermediate and advanced levels since they have quite a lot of language. </p>
        <h5>Patchwork sequence</h5>
        <p>Patchwork lessons include all ESA elements, but can do so more than once and in various orders.
          A sequence such as E.A.A.S.S.E.S.A would be perfectly possible. EAAASEA Patchwork is commonly used in the class of intermediate and advanced levels, 
          because they probably reflect the way we learn rather chaotically and not always in a straight line. </p>


      </div>
      <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
      </div>
    </div>
  
  </header>

templates/hello.html
{% extends "base.html" %}

{% block title %}- Test{% endblock %}

{% block header %}
  <h1 class="header-title">You are now logged in.</h1>
{% endblock %}

{% block content %}
  
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %}- Home{% endblock %}

{% block header %}
  <h1 class="header-title">Lesson Planner</h1>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="col s12 m6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">Lesson Plans</span>
          <p>{{ lesson_list.count }}</p>
        </div>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">Active Users</span>
          <p>{{ num_users }}</p>
        </div>
      </div>
    </div>
  </div>

  <!-- Featured Lessons -->
  <div class="row">
    <div class="col s12">
      <h2>Featured Lesson Plans</h2>
      <ul class="collection">
        {% for lesson in featured %}
          <a href="{% url 'lessons:lesson_detail' pk=lesson.id %}" class="collection-item">
            {% if lesson.tags %}
              {% for tag in lesson.tags.all %}
                <span class="badge blue white-text">
                  {{ tag.name }}
                </span>
              {% endfor %}
            {% endif %}
            {{ lesson.title }}
          </a>
        {% empty %}
          <li class="collection-item">No featured lessons yet.</li>
        {% endfor %}
          <a href="{% url 'lessons:lesson_list' %}" class="collection-item">All Lesson Plans >></a>
      </ul>
    </div>
  </div>

  <div class="row">
    <!-- Popular Tags -->
    <div class="col s12 m6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">Popular Tags</span>
          <ul class="collection">
            {% for tag in popular_tags %}
              <a href="{% url 'lessons:tag_detail' slug=tag.slug %}" class="collection-item">
                {{ tag.name }}
                <span class="new badge" data-badge-caption="lesson{{ tag.lessons.all.count|pluralize }}">{{ tag.lessons.all.count }}</span>
              </a>
            {% empty %}
              <li class="collection-item">No tags yet.</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <!-- Popular Books -->
    <div class="col s12 m6">
      <div class="card">
        <div class="card-content">
          <span class="card-title">Popular Books</span>
          <ul class="collection">
            {% for book in popular_books %}
              <a href="{% url 'lessons:book_detail' slug=book.slug %}" class="collection-item">
                {{ book.title }}
                <span class="new badge" data-badge-caption="lesson{{ book.lessons.all.count|pluralize }}">{{ book.lessons.all.count }}</span>
              </a>
            {% empty %}
              <li class="collection-item">No books yet.</li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Latests Lessons -->
  <div class="row">
    <div class="col s12">
      <h2>Latest Lesson Plans</h2>
      <ul class="collection">
        {% for lesson in latest %}
          <a href="{% url 'lessons:lesson_detail' pk=lesson.id %}" class="collection-item">
            {% if lesson.tags %}
              {% for tag in lesson.tags.all %}
                <span class="badge blue white-text">
                  {{ tag.name }}
                </span>
              {% endfor %}
            {% endif %}
            {{ lesson.title }}
          </a>
        {% empty %}
          <li class="collection-item">No lessons yet.</li>
        {% endfor %}
          <a href="{% url 'lessons:lesson_list' %}" class="collection-item">All Lesson Plans >></a>
      </ul>
    </div>
  </div>
{% endblock %}

templates/test.html
{% extends "base.html" %}

{% block title %}- Test{% endblock %}

{% block header %}
  <h1 class="header-title">You are now logged in.</h1>
{% endblock %}

{% block content %}
  
{% endblock %}

templates/thanks.html
{% extends "base.html" %}

{% block title %}- Thank You{% endblock %}

{% block header %}
  <h1 class="header-title">Thanks for visiting. Come back soon.</h1>
{% endblock %}

{% block content %}
  
{% endblock %}