lesson_planner/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("laoban/", admin.site.urls),
    path("", views.HomePage.as_view(), name="home"),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("hello/", views.HelloPage.as_view(), name="hello"),
    path("goodbye/", views.GoodbyePage.as_view(), name="goodbye"),
    path("games/", views.GamesPage.as_view(), name="games"),
    path("about/", views.AboutPage.as_view(), name="about"),
    path("lessons/", include("lessons.urls", namespace="lessons")),
]

lessons/urls.py
"""Urls file for lessons app"""
from django.urls import path
from . import views

app_name = "lessons"

urlpatterns = [
    path("all/", views.LessonListView.as_view(), name="lesson_list"),
    path("id/<pk>/", views.LessonDetailView.as_view(), name="lesson_detail"),
    path("create-basic/", views.CreateBasicLessonView.as_view(), name="create_basic"),
    path("create-arrow/", views.CreateArrowLessonView.as_view(), name="create_arrow"),
    path(
        "create-boomerang/",
        views.CreateBoomerangLessonView.as_view(),
        name="create_boomerang",
    ),
    path(
        "create-patchwork/",
        views.CreatePatchworkLessonView.as_view(),
        name="create_patchwork",
    ),
    path("delete/<pk>/", views.DeleteLessonView.as_view(), name="delete"),
    path("update/<pk>/", views.UpdateLessonView.as_view(), name="update_basic"),
    path(
        "update-arrow/<pk>/", views.UpdateArrowLessonView.as_view(), name="update_arrow"
    ),
    path(
        "update-boomerang/<pk>/",
        views.UpdateBoomerangLessonView.as_view(),
        name="update_boomerang",
    ),
    path(
        "update-patchwork/<pk>/",
        views.UpdatePatchworkLessonView.as_view(),
        name="update_patchwork",
    ),
    path("by/<username>/", views.LessonListByUser.as_view(), name="by_user"),
    path("with-tag/all/", views.TagListView.as_view(), name="tag_list"),
    path("with-tag/<slug:slug>/", views.TagDetailView.as_view(), name="tag_detail"),
    path("from-book/all/", views.BookListView.as_view(), name="book_list"),
    path("from-book/<slug:slug>/", views.BookDetailView.as_view(), name="book_detail"),
]

lessons/forms.py
"""Lesson forms module"""
from django import forms
from .models import Lesson


class CreateBasicLessonForm(forms.ModelForm):
    """Form to create new Basic lesson plans"""

    class Meta:
        model = Lesson
        fields = (
            "title",
            "tags",
            "book",
            "lesson_number",
            "lesson_duration",
            "lesson_objectives",
            "resources",
            "content",
            "video_url",
        )


class CreateArrowLessonForm(forms.ModelForm):
    """Form to create new ESA Arrow lesson plans"""

    class Meta:
        model = Lesson
        fields = (
            "title",
            "tags",
            "book",
            "lesson_number",
            "lesson_duration",
            "lesson_objectives",
            "resources",
            "video_url",
            # E-R-S-A-W
            "engage_time",
            "engage_description",
            "review_time",
            "review_description",
            "study_time",
            "study_description",
            "activate_time",
            "activate_description",
            "wrap_up_time",
            "wrap_up_description",
        )


class CreateBoomerangLessonForm(forms.ModelForm):
    """Form to create new ESA Boomerang lesson plans"""

    class Meta:
        model = Lesson
        fields = (
            "title",
            "tags",
            "book",
            "lesson_number",
            "lesson_duration",
            "lesson_objectives",
            "resources",
            "video_url",
            # E-A-R-S-C-A2-W
            "engage_time",
            "engage_description",
            "activate_time",
            "activate_description",
            "review_time",
            "review_description",
            "study_time",
            "study_description",
            "activate_time2",
            "activate_description2",
            "wrap_up_time",
            "wrap_up_description",
        )


class CreatePatchworkLessonForm(forms.ModelForm):
    """Form to create new ESA Patchwork lesson plans"""

    class Meta:
        model = Lesson
        fields = (
            "title",
            "tags",
            "book",
            "lesson_number",
            "lesson_duration",
            "lesson_objectives",
            "resources",
            "video_url",
            # E-R-A-A2-S-S2-E2-A3-W
            "engage_time",
            "engage_description",
            "review_time",
            "review_description",
            "activate_time",
            "activate_description",
            "activate_time2",
            "activate_description2",
            "study_time",
            "study_description",
            "engage_time2",
            "engage_description2",
            "activate_time3",
            "activate_description3",
            "wrap_up_time",
            "wrap_up_description",
        )

lessons/views.py
"""Views for lesson app"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from lessons.models import Book, Lesson, Tag
from .forms import (
    CreateBasicLessonForm,
    CreateArrowLessonForm,
    CreateBoomerangLessonForm,
    CreatePatchworkLessonForm,
)

User = get_user_model()  # pylint:disable=invalid-name

# pylint:disable=too-many-ancestors
# Create your views here.
class LessonListView(ListView):
    """Lesson list view"""

    model = Lesson
    context_object_name = "lesson_list"


class LessonDetailView(DetailView):
    """Lesson detail view"""

    model = Lesson


class LessonListByUser(ListView):
    """Lesson list by user view"""

    model = Lesson
    # template_name = "user_lesson_list.html"

    def get_queryset(self):  # pylint:disable=attribute-defined-outside-init
        try:
            self.lesson_author = User.objects.prefetch_related("lessons").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.lesson_author.lessons.all()

    # pylint:disable=arguments-differ
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["lesson_author"] = self.lesson_author
        return context


class CreateBasicLessonView(LoginRequiredMixin, CreateView):
    """Create a Basic lesson view"""

    form_class = CreateBasicLessonForm
    model = Lesson
    template_name = "lessons/forms/lesson_form_basic.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.base = True
        self.object.save()
        return super().form_valid(form)


class CreateArrowLessonView(LoginRequiredMixin, CreateView):
    """Create an Arrow lesson view"""

    form_class = CreateArrowLessonForm
    model = Lesson
    template_name = "lessons/forms/lesson_form_arrow.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.arrow = True
        self.object.save()
        return super().form_valid(form)


class CreateBoomerangLessonView(LoginRequiredMixin, CreateView):
    """Create a Boomerang lesson view"""

    form_class = CreateBoomerangLessonForm
    model = Lesson
    template_name = "lessons/forms/lesson_form_boomerang.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.boomerang = True
        self.object.save()
        return super().form_valid(form)


class CreatePatchworkLessonView(LoginRequiredMixin, CreateView):
    """Create a Patchwork lesson view"""

    form_class = CreatePatchworkLessonForm
    model = Lesson
    template_name = "lessons/forms/lesson_form_patchwork.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.patchwork = True
        self.object.save()
        return super().form_valid(form)


class DeleteLessonView(LoginRequiredMixin, DeleteView):
    """Delete lesson view"""

    model = Lesson
    success_url = reverse_lazy("lessons:lesson_list")

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     return queryset.filter(author_id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post deleted.")
        return super().delete(*args, **kwargs)


class UpdateLessonView(UpdateView):
    """Update Basic lesson view"""

    model = Lesson
    fields = (
        "title",
        "tags",
        "book",
        "lesson_number",
        "lesson_duration",
        "lesson_objectives",
        "resources",
        "content",
        "video_url",
    )
    template_name = "lessons/forms/update_forms/lesson_update_basic.html"


class UpdateArrowLessonView(UpdateView):
    """Update Arrow lesson view"""

    model = Lesson
    fields = (
        "title",
        "tags",
        "book",
        "lesson_number",
        "lesson_duration",
        "lesson_objectives",
        "resources",
        "video_url",
        # E-R-S-A-W
        "engage_time",
        "engage_description",
        "review_time",
        "review_description",
        "study_time",
        "study_description",
        "activate_time",
        "activate_description",
        "wrap_up_time",
        "wrap_up_description",
    )
    template_name = "lessons/forms/update_forms/lesson_update_arrow.html"


class UpdateBoomerangLessonView(UpdateView):
    """Update Boomerang lesson view"""

    model = Lesson
    fields = (
        "title",
        "tags",
        "book",
        "lesson_number",
        "lesson_duration",
        "lesson_objectives",
        "resources",
        "video_url",
        # E-A-R-S-C-A2-W
        "engage_time",
        "engage_description",
        "activate_time",
        "activate_description",
        "review_time",
        "review_description",
        "study_time",
        "study_description",
        "activate_time2",
        "activate_description2",
        "wrap_up_time",
        "wrap_up_description",
    )
    template_name = "lessons/forms/update_forms/lesson_update_boomerang.html"


class UpdatePatchworkLessonView(UpdateView):
    """Update Patchwork lesson view"""

    model = Lesson
    fields = (
        "title",
        "tags",
        "book",
        "lesson_number",
        "lesson_duration",
        "lesson_objectives",
        "resources",
        "video_url",
        # E-R-A-A2-S-S2-E2-A3-W
        "engage_time",
        "engage_description",
        "review_time",
        "review_description",
        "activate_time",
        "activate_description",
        "activate_time2",
        "activate_description2",
        "study_time",
        "study_description",
        "engage_time2",
        "engage_description2",
        "activate_time3",
        "activate_description3",
        "wrap_up_time",
        "wrap_up_description",
    )
    template_name = "lessons/forms/update_forms/lesson_update_patchwork.html"


class TagListView(ListView):
    """Tag list view"""

    model = Tag


class TagDetailView(DetailView):
    """Tag detail view"""

    model = Tag


class BookListView(ListView):
    """Book list view"""

    model = Book


class BookDetailView(DetailView):
    """Book detail view"""

    model = Book

lessons/templates/lessons/book_detail.html
{% extends 'base.html' %}

{% block title %}
  - Book: {{ book.title }}
{% endblock %}

{% block header %}
  <h1 class="header-title">Lessons from book: {{ book.title }}</h1>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12">
      <ul class="collection">
        {% for lesson in book.lessons.all %}
          <a href="{% url 'lessons:lesson_detail' pk=lesson.id %}" class="collection-item">{{ lesson.title }}</a>
        {% empty %}
          <li class="collection-item">No lessons from this book.</li>
        {% endfor %}
        <a href="{% url 'lessons:book_list' %}" class="collection-item">All books >></a>
      </ul>
    </div>
  </div>
{% endblock %}

lessons/templates/lessons/book_list.html
{% extends 'base.html' %}

{% block title %}
  - All Books
{% endblock %}

{% block header %}
  <h1 class="header-title">All Books</h1>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12">
      <ul class="collection">
        {% for book in book_list %}
          <a href="{% url 'lessons:book_detail' slug=book.slug %}" class="collection-item">{{ book.title }}</a>
        {% empty %}
          <li class="collection-item">No books yet.</li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

lessons/templates/lessons/lesson_base.html
{% extends 'base.html' %}

{% block title %}
  {% block lesson_title %}{% endblock %}
{% endblock %}

{% block header %}
  <h1 class="header-title">{% block lesson_header %}{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="lesson">
    {% block lesson_content %}{% endblock %}
  </div>
{% endblock %}

lessons/templates/lessons/lesson_confirm_delete.html
{% extends 'lessons/lesson_base.html' %}

{% block lesson_title %}- Confirm Delete {% endblock %}

{% block lesson_header %}
  Confirm Delete
{% endblock %}

{% block lesson_content %}
  <h3>Are you sure you want to delete this lesson?</h3>
  <div class="lesson">
     {{ object.title }}
  </div>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
    <a href="{% url 'lessons:lesson_detail' pk=object.pk %}">Cancel</a>
  </form>
{% endblock %}

lessons/templates/lessons/lesson_detail.html
{% extends 'lessons/lesson_base.html' %}
{% load markdownify %}

{% block lesson_title %}- Lesson: {{ lesson.title }} {% endblock %}

{% block lesson_header %}
  <div class="card">
    <div class="card-content">
      <span class="card-title">Lesson:</span>
      <p>{{ lesson.title }}</p>
    </div>
    <div class="card-action">
      {% if user.is_authenticated and user == lesson.author %}
        <div class="lesson-buttons center">
          {% if lesson.base %}
            <a class="waves-effect waves-light btn" href="{% url 'lessons:update_basic' pk=lesson.id %}">
              <i class="material-icons left">edit</i>Edit
            </a>
          {% elif lesson.arrow %}
            <a class="waves-effect waves-light btn" href="{% url 'lessons:update_arrow' pk=lesson.id %}">
              <i class="material-icons left">edit</i>Edit
            </a>
          {% elif lesson.boomerang %}
            <a class="waves-effect waves-light btn" href="{% url 'lessons:update_boomerang' pk=lesson.id %}">
              <i class="material-icons left">edit</i>Edit
            </a>
          {% elif lesson.patchwork %}
            <a class="waves-effect waves-light btn" href="{% url 'lessons:update_patchwork' pk=lesson.id %}">
              <i class="material-icons left">edit</i>Edit
            </a>
          {% endif %}
          <a class="waves-effect waves-light btn" href="{% url 'lessons:delete' pk=lesson.id %}">
              <i class="material-icons left">delete</i>Delete
          </a>
        </div>  
      {% endif %}
    </div>
  </div>
{% endblock %}

{% block lesson_content %}
  

  <h3>Information</h3>

  <ul class="collection z-depth-1">
    <li class="collection-item">
      <i class="material-icons left">account_circle</i>
      Author: <a href="{% url 'lessons:by_user' username=lesson.author.username %}">{{ lesson.author }}</a>
    </li>

    <li class="collection-item">
      <i class="material-icons left">date_range</i>
      {{ lesson.created_at }}
    </li>

    <li class="collection-item">
      <i class="material-icons left">local_offer</i>
      {% for tag in lesson.tags.all %}
        <span class="badge left blue">
          <a href="{% url 'lessons:tag_detail' slug=tag.slug %}" class="white-text">
            #{{ tag.name }}
          </a>
        </span>
        &nbsp;
      {% empty %}
        No tags
      {% endfor %}
    </li>

    <li class="collection-item">
      <i class="material-icons left">book</i>
      {% if lesson.book %}
        <a href="{% url 'lessons:book_detail' slug=lesson.book.slug %}">{{ lesson.book }}</a>
      {% else %}
        No book
      {% endif %}
    </li>

    <li class="collection-item">
      <i class="material-icons left">info</i>
      {% if lesson.book %}
        Lesson number: {{ lesson.lesson_number }}
      {% else %}
        Lesson number: -
      {% endif %}
    </li>

    <li class="collection-item">
      <i class="material-icons left">alarm</i>
      {% if lesson.book %}
        Lesson duration: {{ lesson.lesson_duration }} minutes.
      {% else %}
        Lesson duration: -
      {% endif %}
    </li>
  </ul>

  <div class="row">
    <div class="col s12 m6">
      <div class="card small">
        <div class="card-content">
          <span class="card-title">Lesson objectives</span>
          <p>{{ lesson.lesson_objectives|markdownify }}</p>
        </div>
      </div>
    </div>
    <div class="col s12 m6">
      <div class="card small">
        <div class="card-content">
          <span class="card-title">Lesson resources</span>
          <p>{{ lesson.resources|markdownify }}</p>
        </div>
      </div>
    </div>
  </div>
  
  <div class="lesson-content">
    <!-- if base lesson -->
    {% if lesson.base %}
      <h3>Content</h3>
      {{ lesson.content|markdownify }}
    <!-- if arrow lesson -->
    {% elif lesson.arrow %}
      {% include 'lessons/lesson_stages_arrow.html' %}
    <!-- if boomerang lesson -->
    {% elif lesson.boomerang %}
      {% include 'lessons/lesson_stages_boomerang.html' %}
    <!-- if patchwork lesson -->
    {% elif lesson.patchwork %}
      {% include 'lessons/lesson_stages_patchwork.html' %}
    {% endif %}
  </div>

  <div class="lesson-video">
    <h3>Video</h3>
    {% if lesson.embed_video_url %}
    <iframe width="640" 
      height="385"
      src="{{ lesson.embed_video_url }}"
      class="lesson-video-iframe">
    </iframe>
    {% else %}
      No video for this lesson.
    {% endif %}

  </div>
{% endblock %}

lessons/templates/lessons/lesson_form.html
{% extends 'lessons/lesson_base.html' %}

{% block head %}{% endblock %}

{% block lesson_title %}- New Lesson Plan {% endblock %}

{% block lesson_header %}
  Add a New Lesson Plan
{% endblock %}

{% block lesson_content %}
  <div class="row">
    <form action="{% url 'lessons:create_base' %}" method="POST" class="col s12">
      {% csrf_token %}
      {{ form.non_field_errors }}
      
      <!-- title filed -->
      <div class="row">
        <div class="input-field col s12">
          <ul>
          {% for error in form.title.errors %}
            <span class="helper-text red-text">{{ error }}</span>
          {% endfor %}
          </ul>
          <label for="{{ form.title.id_for_label }}">{{ form.title.label }} *</label>
          {{ form.title }}
          <span class="helper-text" data-error="wrong" data-success="right">{{ form.title.help_text  }}</span>
        </div>
      </div>

      <!-- tags field & books field -->
      <div class="row">
        <div class="input-field col s6">
          {% for error in form.tags.errors %}
            <span class="helper-text red-text">{{ error }}</span>
          {% endfor %}

          {{ form.tags }}
          <label for="{{ form.tags.id_for_label }}">{{ form.tags.label }}</label>
        </div>
        <div class="input-field col s6">
          {% for error in form.tags.errors %}
            <span class="helper-text red-text">{{ error }}</span>
          {% endfor %}

          {{ form.book }}
          <label for="{{ form.book.id_for_label }}">{{ form.book.label }}</label>
        </div>
      </div>

      <!-- lesson number & lesson duration   -->
      <div class="row">
        <div class="input-field col s6">
          {% for error in form.title.errors %}
            {{ error }}
          {% endfor %}
          <label for="{{ form.lesson_number.id_for_label }}">{{ form.lesson_number.label }}</label>
          {{ form.lesson_number }}
          <span class="helper-text" data-error="wrong" data-success="right">{{ form.lesson_number.help_text  }}</span>
        </div>
        <div class="input-field col s6">
          <label for="{{ form.lesson_duration.id_for_label }}">{{ form.lesson_duration.label }}</label>
          {{ form.lesson_duration }}
          <span class="helper-text" data-error="wrong" data-success="right">{{ form.lesson_duration.help_text  }}</span>
        </div>
      </div>
      
      <!-- lesson objectives -->
      <div class="row">
        <div class=" input-field col s12 ">
          {% for error in form.title.errors %}
            {{ error }}
          {% endfor %}
          <textarea 
            name="{{ form.lesson_objectives.html_name }}"
            id="{{ form.lesson_objectives.id_for_label }}" 
            class="materialize-textarea">{{ form.lesson_objectives.value }}</textarea>
          <label for="{{ form.lesson_objectives.id_for_label }}">{{ form.lesson_objectives.label }}</label>
        </div>
      </div>

      <!-- resources -->
      <div class="row">
        <div class=" input-field col s12 ">
          {% for error in form.title.errors %}
            {{ error }}
          {% endfor %}
          <textarea 
            id="{{ form.resources.id_for_label }}" 
            class="materialize-textarea"
            name="{{ form.resources.html_name }}">{{ form.resources.value }}</textarea>
          <label for="{{ form.resources.id_for_label }}">{{ form.resources.label }}</label>
        </div>
      </div>

      <!-- content -->
      <div class="row">
        <div class=" input-field col s12 ">
          {% for error in form.content.errors %}
            <span class="helper-text red-text" >{{ error }}</span>
          {% endfor %}
          <textarea 
            id="{{ form.content.id_for_label }}" 
            class="materialize-textarea"
            name="{{ form.content.html_name }}">{{ form.content.value }}</textarea>
          <label for="{{ form.content.id_for_label }}">{{ form.content.label }}</label>
        </div>
      </div>

      <!-- video url -->
      <div class="row">
        <div class=" input-field col s12 ">
          {% for error in form.title.errors %}
            {{ error }}
          {% endfor %}
          {{ form.video_url }}
          <label for="{{ form.video_url.id_for_label }}">{{ form.video_url.label }}</label>
        </div>
      </div>

      <input type="submit" class="btn" value="Add Lesson Plan">
    </form>
  </div>

  {% include 'lessons/formatting_help.html' %}
  
{% endblock %}

lessons/templates/lessons/lesson_list.html
{% extends 'lessons/lesson_base.html' %}

{% block lesson_title %}- Lessons Plans {% endblock %}

{% block lesson_header %}
  Lesson Plans
{% endblock %}

{% block lesson_content %}
  
  <div class="row">
    <div class="col s12">
      {% for lesson in lesson_list %}
        <div class="card">
          <div class="card-content">
            <span class="card-title"><a href="{% url "lessons:lesson_detail" lesson.id %}">{{ lesson.title }}</a></span>
            <p>created by <strong><a href="{% url 'lessons:by_user' username=lesson.author %}">{{ lesson.author }}</a></strong> 
              on <strong>{{ lesson.created_at }}</strong>
              {% if lesson.tags %}
                {% for tag in lesson.tags.all %}
                  <span class="badge blue white-text">
                    {{ tag.name }}
                  </span>
                {% endfor %}
              {% endif %}
            </p>
          </div>
        </div>
      {% empty %}
        <p>No lesson plans yet</p>
      {% endfor %}
    </div>
  </div>


<ul class="lesson-list">
    {% for lesson in lesson_list %}
      <li class="lesson-list-item">
        
        
      </li>
    {% empty %}
      <p>No lesson plans yet</p>
    {% endfor %}
  </ul>
{% endblock %}

lessons/templates/lessons/lesson_stages_arrow.html
{% load markdownify %}
<h3>Lesson Stages</h3>
<ul class="collection">

  <!-- Engage  -->
  <li class="collection-item light-blue lighten-4">
    1. Engage <span class="new badge" data-badge-caption="mins">{{ lesson.engage_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.engage_description|markdownify }}</li>
  
  <!-- Review -->
  <li class="collection-item light-blue lighten-4">
    2. Review <span class="new badge" data-badge-caption="mins">{{ lesson.review_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.review_description|markdownify }}</li>

  <!-- Study -->
  <li class="collection-item light-blue lighten-4">
    3. Study<span class="new badge" data-badge-caption="mins">{{ lesson.study_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.study_description|markdownify }}</li>

  <!-- Activate -->
  <li class="collection-item light-blue lighten-4">
    4. Activate<span class="new badge" data-badge-caption="mins">{{ lesson.activate_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.activate_description|markdownify }}</li>

  <!-- Wrap Up -->
  <li class="collection-item light-blue lighten-4">
    5. Wrap Up<span class="new badge" data-badge-caption="mins">{{ lesson.wrap_up_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.wrap_up_description|markdownify }}</li>
</ul>

lessons/templates/lessons/lesson_stages_boomerang.html
{% load markdownify %}
<h3>Lesson Stages</h3>
<ul class="collection">

  <!-- Engage  -->
  <li class="collection-item light-blue lighten-4">
    1. Engage <span class="new badge" data-badge-caption="mins">{{ lesson.engage_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.engage_description|markdownify }}</li>

  <!-- Activate -->
  <li class="collection-item light-blue lighten-4">
    2. Activate<span class="new badge" data-badge-caption="mins">{{ lesson.activate_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.activate_description|markdownify }}</li>
  
  <!-- Review -->
  <li class="collection-item light-blue lighten-4">
    3. Review <span class="new badge" data-badge-caption="mins">{{ lesson.review_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.review_description|markdownify }}</li>

  <!-- Study -->
  <li class="collection-item light-blue lighten-4">
    4. Study<span class="new badge" data-badge-caption="mins">{{ lesson.study_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.study_description|markdownify }}</li>

  <!-- Activate -->
  <li class="collection-item light-blue lighten-4">
    5. Activate 2<span class="new badge" data-badge-caption="mins">{{ lesson.activate_time2 }}</span>
  </li>
  <li class="collection-item">{{ lesson.activate_description2|markdownify }}</li>

  <!-- Wrap Up -->
  <li class="collection-item light-blue lighten-4">
    6. Wrap Up<span class="new badge" data-badge-caption="mins">{{ lesson.wrap_up_time }}</span>
  </li>
  <li class="collection-item">{{ lesson.wrap_up_description|markdownify }}</li>
</ul>

lessons/templates/lessons/tag_detail.html
{% extends 'base.html' %}

{% block title %}
  - Tag: {{ tag.name }}
{% endblock %}

{% block header %}
  <h1 class="header-title">Lesson with tag: {{ tag.name }}</h1>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12">
      <ul class="collection">
        {% for lesson in tag.lessons.all %}
          <a href="{% url 'lessons:lesson_detail' pk=lesson.id %}" class="collection-item">{{ lesson.title }}</a>
        {% empty %}
          <li class="collection-item">No lessons with this tag.</li>
        {% endfor %}
        <a href="{% url 'lessons:tag_list' %}" class="collection-item">All tags >></a>
      </ul>
    </div>
  </div>
{% endblock %}

lessons/templates/lessons/tag_list.html
{% extends 'base.html' %}

{% block title %}
  - All Tags
{% endblock %}

{% block header %}
  <h1 class="header-title">All Tags</h1>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col s12">
      <ul class="collection">
          {% for tag in tag_list %}
          <a href="{% url 'lessons:tag_detail' slug=tag.slug %}" class="collection-item">{{ tag.name }}</a>
        {% empty %}
          <li class="collection-item">No tags yet.</li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}